version: '2'
services:
    interaction-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/interaction/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=interaction
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
